name: Adaptive Test Distribution
description: Balances Playwright tests based on historical execution times
outputs:
  matrix:
    description: "Test distribution matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash

      run: npm ci

    - name: Load Historical Test Execution Data from Cache
      id: check-cache
      uses: actions/cache@v3
      with:
        path: test-times.json  # Path to cache
        key: ${{ runner.os }}-test-times-${{ hashFiles('**/*.js') }}  # Cache key based on JS files or any dependencies
        restore-keys: |
          ${{ runner.os }}-test-times-

      continue-on-error: true # Allow the job to continue even if cache misses

    - name: Generate Default Test Durations if No Cache Exists
      if: steps.check-cache.outputs.cache-hit != 'true'
      run: |
        echo "Cache miss. Generating default test times."
        # List all test files and create the default execution times JSON
        find tests/ -name '*.spec.ts' | jq -R -s -c 'split("\n") | map({test: ., time: 5})' > test-times.json
      shell: bash

    - name: Compute Balanced Test Groups
      id: set-matrix
      shell: bash
      run: |
        MATRIX=$(node .github/actions/adaptive-distribution/split-tests-by-time.js test-times.json 4) # number of shards set here
        echo "matrix=$MATRIX" >> $GITHUB_ENV


    - name: Save Test Execution Data to Cache
      uses: actions/cache@v3
      with:
        path: test-times.json
        key: ${{ runner.os }}-test-times-${{ hashFiles('**/*.js') }} # Cache key
