name: Matrix-Based Test Distribution
description: Splits Playwright tests into shards using GitHub Actions matrix

inputs: {}

outputs:
  matrix:
    description: "Test distribution matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Generate and split test list into shards
      id: set-matrix
      shell: bash
      run: |
        NUM_SHARDS=4

        TEST_FILES=$(find tests -type f -name "*.spec.ts" | jq -R -s -c 'split("\n")[:-1]')
        if [ -z "$TEST_FILES" ] || [ "$TEST_FILES" = "[]" ]; then
          echo "⚠️ No test files found"
          echo "matrix=[]" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        SHARD_MATRIX=$(echo "$TEST_FILES" | jq -c --argjson n "$NUM_SHARDS" '
          . as $all
          | ($all | length) as $total
          | [range(0; $n) |
              $all[
                ((. * $total) / $n | floor)
                :
                (((. + 1) * $total) / $n | floor)
              ]
            ]
        ')
        CLEANED_MATRIX=$(echo "$SHARD_MATRIX" | jq -c '[.[] | select(length > 0)] | map({ testFile: . })')
        printf "matrix=%s" "$CLEANED_MATRIX" >> "$GITHUB_OUTPUT"
        echo 'cat GITHUB_OUTPUT'
        cat $GITHUB_OUTPUT

    - name: Debug matrix
      shell: bash
      run: |
        echo " steps.set-matrix.outputs.matrix "
        echo "${{ steps.set-matrix.outputs.matrix }}"
