name: Single Shard Execution
on:
  workflow_dispatch:
jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest #(microsoft/playwright)
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-jammy
    #this needs to be here for Firefox
    env:
      HOME: /root
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.recipe1.ts

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 1

      - name: Notify Slack (Job Success)
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # eng-monitoring-ops
          channel-id: "C03CX7K9JJG"
          slack-message: "✅ Playwright tests passed for ${{ github.repository }} - ${{ github.ref }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_SEND_TOKEN }}


      - name: Notify Slack (Job Success)
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # eng-monitoring-ops
          channel-id: "C03CX7K9JJG"
          slack-message: "❌ Playwright tests failed for ${{ github.repository }} - ${{ github.ref }}. Check logs for details."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_SEND_TOKEN }}
