apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-argo-workflows-workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    pvc:
      archiveLogs: true
      mountPath: /mnt/playwright-reports
      claimName: playwright-reports-pvc
